spring.application.name=ecommerce

# ===============================
# H2 DATABASE
# ===============================
spring.datasource.url=jdbc:h2:mem:ecommerce
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Create/update tables automatically
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console


# Local development secret
jwt.secret=local-development-secret-change-this-32bytes
jwt.expiration-ms=86400000

app.admin.email=admin@example.com
app.admin.password=Admin@123

project.image=images
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB